/-
Copyright (c) 2020 Bhavik Mehta, E. W. Ayers. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Bhavik Mehta, E. W. Ayers
-/

import category_theory.sites.grothendieck
import category_theory.sites.pretopology
import category_theory.full_subcategory
import category_theory.types

universes v u
namespace category_theory

open category_theory category sieve classical

variables {C : Type u} [category.{v} C]

namespace sheaf
namespace grothendieck_topology

variables {P : Cᵒᵖ ⥤ Type v}
variables {X Y : C} {S : sieve X} {R : arrows_with_codomain X}
variables (J J₂ : grothendieck_topology C)

/--
A family of elements for a presheaf `P` given a collection of arrows `R` with fixed codomain `X`
consists of an element of `P Y` for every `f : Y ⟶ X` in `R`.
A presheaf is a sheaf (resp, separated) if every *consistent* family of elements has exactly one
(resp, at most one) amalgamation.
-/
def family_of_elements (P : Cᵒᵖ ⥤ Type v) (R : arrows_with_codomain X) :=
Π ⦃Y : C⦄ (f : Y ⟶ X), R f → P.obj (opposite.op Y)

/--
A family of elements for a presheaf on the arrow set `R₂` can be restricted to a smaller collection
of arrows `R₁`.
-/
def restrict_family {R₁ R₂ : arrows_with_codomain X} (h : R₁ ≤ R₂) :
  family_of_elements P R₂ → family_of_elements P R₁ :=
λ x Y f hf, x f (h _ hf)

/--
A family of elements for the arrow set `R` is consistent if for any `f₁ : Y₁ ⟶ X` and `f₂ : Y₂ ⟶ X`
in `R`, and any `g₁ : Z ⟶ Y₁` and `g₂ : Z ⟶ Y₂`, if the square `g₁ ≫ f₁ = g₂ ≫ f₂` commutes then
the elements of `P Z` obtained by restricting the element of `P Y₁` along `g₁` and restricting
the element of `P Y₂` along `g₂` are the same.
-/
def is_consistent (x : family_of_elements P R) : Prop :=
∀ ⦃Y₁ Y₂ Z⦄ (g₁ : Z ⟶ Y₁) (g₂ : Z ⟶ Y₂) ⦃f₁ : Y₁ ⟶ X⦄ ⦃f₂ : Y₂ ⟶ X⦄
  (h₁ : R f₁) (h₂ : R f₂), g₁ ≫ f₁ = g₂ ≫ f₂ → P.map g₁.op (x f₁ h₁) = P.map g₂.op (x f₂ h₂)

/-- The restriction of a consistent family is consistent. -/
lemma restrict_family_is_consistent {R₁ R₂ : arrows_with_codomain X} (h : R₁ ≤ R₂)
  (x : family_of_elements P R₂) : is_consistent x → is_consistent (restrict_family h x) :=
λ q Y₁ Y₂ Z g₁ g₂ f₁ f₂ h₁ h₂ comm, q g₁ g₂ (h _ h₁) (h _ h₂) comm

/-- Extend a family of elements to the sieve generated by an arrow set. -/
noncomputable def extend_family (x : family_of_elements P R) :
  family_of_elements P (generate R) :=
λ Z f hf, P.map (some (some_spec hf)).op (x _ (some_spec (some_spec (some_spec hf))).1)

/-- The extension of a consistent family to the generated sieve is consistent. -/
lemma extend_family_is_consistent (x : family_of_elements P R) (hx : is_consistent x) :
  is_consistent (extend_family x) :=
begin
  intros Y₁ Y₂ Z g₁ g₂ f₁ f₂ h₁ h₂ comm,
  rw [←(some_spec (some_spec (some_spec h₁))).2, ←(some_spec (some_spec (some_spec h₂))).2,
      ←assoc, ←assoc] at comm,
  dsimp [extend_family],
  rw [← functor_to_types.map_comp_apply, ← functor_to_types.map_comp_apply],
  apply hx _ _ _ _ comm,
end

/-- The extension of a family agrees with the original family. -/
lemma extend_agrees {x : family_of_elements P R} (t : is_consistent x) {f : Y ⟶ X} (hf : R f) :
  extend_family x f ⟨_, 𝟙 _, f, hf, id_comp _⟩ = x f hf :=
begin
  have h : (generate R) f := ⟨_, _, _, hf, id_comp _⟩,
  change P.map (some (some_spec h)).op (x _ _) = x f hf,
  rw t (some (some_spec h)) (𝟙 _) _ hf _,
  { simp },
  simp_rw [id_comp],
  apply (some_spec (some_spec (some_spec h))).2,
end

/-- The restriction of an extension is the original. -/
lemma restrict_extend {x : family_of_elements P R} (t : is_consistent x) :
  restrict_family (le_generate R) (extend_family x) = x :=
begin
  ext Y f hf,
  exact extend_agrees t hf,
end

/--
If the arrow set for a family of elements is actually a sieve (i.e. it is downward closed) then the
consistency condition can be simplified.
This is an equivalent condition, see `is_sieve_consistent_iff`.
-/
def is_sieve_consistent (x : family_of_elements P S) : Prop :=
∀ ⦃Y Z⦄ (f : Y ⟶ X) (g : Z ⟶ Y) (hf), x (g ≫ f) (S.downward_closed hf g) = P.map g.op (x f hf)

lemma is_sieve_consistent_iff (x : family_of_elements P S) :
  is_consistent x ↔ is_sieve_consistent x :=
begin
  split,
  { intros h Y Z f g hf,
    simpa using h (𝟙 _) g (S.downward_closed hf g) hf (id_comp _) },
  { intros h Y₁ Y₂ Z g₁ g₂ f₁ f₂ h₁ h₂ k,
    simp_rw [← h f₁ g₁ h₁, k, h f₂ g₂ h₂] }
end

lemma restrict_inj {x₁ x₂ : family_of_elements P (generate R)} (t₁ : is_consistent x₁)
  (t₂ : is_consistent x₂) :
  restrict_family (le_generate R) x₁ = restrict_family (le_generate R) x₂ →
  x₁ = x₂ :=
begin
  intro h,
  ext Z f ⟨Y, f, g, hg, rfl⟩,
  rw is_sieve_consistent_iff at t₁ t₂,
  erw [t₁ g f ⟨_, _, g, hg, id_comp _⟩, t₂ g f ⟨_, _, g, hg, id_comp _⟩],
  congr' 1,
  apply congr_fun (congr_fun (congr_fun h _) g) hg,
end

lemma extend_restrict {x : family_of_elements P (generate R)} (t : is_consistent x) :
  extend_family (restrict_family (le_generate R) x) = x :=
begin
  apply restrict_inj,
  exact extend_family_is_consistent _ (restrict_family_is_consistent (le_generate R) x t),
  exact t,
  rw restrict_extend,
  exact restrict_family_is_consistent (le_generate R) x t,
end

def is_amalgamation_for (x : family_of_elements P R)
  (t : P.obj (opposite.op X)) : Prop :=
∀ ⦃Y : C⦄ (f : Y ⟶ X) (h : R f), P.map f.op t = x f h

lemma is_consistent_of_exists_amalgamation (x : family_of_elements P R)
  (h : ∃ t, is_amalgamation_for x t) : is_consistent x :=
begin
  cases h with t ht,
  intros Y₁ Y₂ Z g₁ g₂ f₁ f₂ h₁ h₂ comm,
  rw [←ht _ h₁, ←ht _ h₂, ←functor_to_types.map_comp_apply, ←op_comp, comm],
  simp,
end

lemma is_amalgamation_for_restrict {R₁ R₂ : arrows_with_codomain X} (h : R₁ ≤ R₂)
  (x : family_of_elements P R₂) (t : P.obj (opposite.op X)) (ht : is_amalgamation_for x t) :
  is_amalgamation_for (restrict_family h x) t :=
λ Y f hf, ht f (h Y hf)

lemma is_amalgamation_for_extend {R : arrows_with_codomain X}
  (x : family_of_elements P R) (t : P.obj (opposite.op X)) (ht : is_amalgamation_for x t) :
  is_amalgamation_for (extend_family x) t :=
begin
  intros Y f hf,
  dsimp [extend_family],
  rw [←ht _, ←functor_to_types.map_comp_apply, ←op_comp, (some_spec (some_spec (some_spec hf))).2],
end

def is_separated_for (P : Cᵒᵖ ⥤ Type v) (R : arrows_with_codomain X) : Prop :=
∀ (x : family_of_elements P R) (t₁ t₂),
  is_consistent x → is_amalgamation_for x t₁ → is_amalgamation_for x t₂ → t₁ = t₂

lemma is_separated_for_iff_generate :
  is_separated_for P R ↔ is_separated_for P (generate R) :=
begin
  split,
  { intros h x t₁ t₂ hx ht₁ ht₂,
    apply h (restrict_family (le_generate R) x) t₁ t₂ _ _ _,
    { exact restrict_family_is_consistent _ x hx },
    { exact is_amalgamation_for_restrict _ x t₁ ht₁ },
    { exact is_amalgamation_for_restrict _ x t₂ ht₂ } },
  { intros h x t₁ t₂ hx ht₁ ht₂,
    apply h (extend_family x),
    { exact extend_family_is_consistent x hx },
    { exact is_amalgamation_for_extend x t₁ ht₁ },
    { exact is_amalgamation_for_extend x t₂ ht₂ } }
end

lemma is_separated_for_top (P : Cᵒᵖ ⥤ Type v) : is_separated_for P (⊤ : arrows_with_codomain X) :=
λ x t₁ t₂ hx h₁ h₂,
begin
  have q₁ := h₁ (𝟙 X) trivial,
  have q₂ := h₂ (𝟙 X) trivial,
  simp only [op_id, functor_to_types.map_id_apply] at q₁ q₂,
  rw [q₁, q₂],
end

structure is_sheaf_for (P : Cᵒᵖ ⥤ Type v) (R : arrows_with_codomain X) :=
(gluing : Π (x : family_of_elements P R), is_consistent x → P.obj (opposite.op X))
(is_valid_gluing : ∀ (x : family_of_elements P R) (H : is_consistent x),
                 is_amalgamation_for x (gluing x H))
(uniqueness : is_separated_for P R)

instance (R : arrows_with_codomain X) : subsingleton (is_sheaf_for P R) :=
⟨begin
  rintros ⟨a, ha₁, ha₂⟩ ⟨b, hb₁, hb₂⟩,
  congr' 1,
  ext x hx,
  exact ha₂ x (a x hx) (b x hx) hx (ha₁ x hx) (hb₁ x hx),
end⟩

lemma is_separated_for_of_is_sheaf_for : is_sheaf_for P R → is_separated_for P R :=
is_sheaf_for.uniqueness

/-- C2.1.3 in Elephant -/
noncomputable def is_sheaf_for_iff_generate {P : Cᵒᵖ ⥤ Type v} {R : arrows_with_codomain X} :
  is_sheaf_for P R ≃ is_sheaf_for P (generate R) :=
{ to_fun := λ t,
  { gluing := λ x hx, t.gluing _ (restrict_family_is_consistent (le_generate R) x hx),
    is_valid_gluing := λ x hx,
    begin
      have := t.is_valid_gluing _ (restrict_family_is_consistent (le_generate R) x hx),
      have := is_amalgamation_for_extend _ _ this,
      rwa extend_restrict hx at this,
    end,
    uniqueness := (is_separated_for_iff_generate).1 t.uniqueness },
  inv_fun := λ t,
  { gluing := λ x hx, t.gluing _ (extend_family_is_consistent x hx),
    is_valid_gluing :=
    begin
      intros x hx,
      have := t.is_valid_gluing _ (extend_family_is_consistent x hx),
      have := is_amalgamation_for_restrict (le_generate R) _ _ this,
      rwa restrict_extend hx at this,
    end,
    uniqueness := (is_separated_for_iff_generate).2 t.uniqueness },
  left_inv := by tidy,
  right_inv := by tidy }

/-- Elephant: C2.1.5(ii) -/
def is_sheaf_for_top_sieve (P : Cᵒᵖ ⥤ Type v) : is_sheaf_for P (⊤ : sieve X) :=
{ gluing := λ x hx, x (𝟙 _) trivial,
  is_valid_gluing := λ x hx Y f hf,
  begin
    rw is_sieve_consistent_iff at hx,
    rw ← hx (𝟙 _) f trivial,
    simp,
  end,
  uniqueness := is_separated_for_top _ }

/-- Elephant: C2.1.5(i) -/
noncomputable def is_sheaf_for_singleton_iso (P : Cᵒᵖ ⥤ Type v) (f : Y ⟶ X) [split_epi f] :
  is_sheaf_for P (arrows_with_codomain.singleton_arrow f) :=
is_sheaf_for_iff_generate.symm
begin
  rw generate_of_singleton_split_epi,
  apply is_sheaf_for_top_sieve,
end

noncomputable def is_sheaf_for_top (P : Cᵒᵖ ⥤ Type v) :
  is_sheaf_for P (⊤ : arrows_with_codomain X) :=
is_sheaf_for_iff_generate.symm
begin
  rw generate_top,
  apply is_sheaf_for_top_sieve P,
end

def is_sheaf_for_subsieve_aux (P : Cᵒᵖ ⥤ Type v) {S : sieve X} {R : arrows_with_codomain X}
  (h : (S : arrows_with_codomain X) ≤ R)
  (hS : is_sheaf_for P S)
  (trans : Π ⦃Y⦄ ⦃f : Y ⟶ X⦄, R f → is_separated_for P (S.pullback f)) :
  is_sheaf_for P R :=
{ gluing := λ x hx, hS.gluing _ (restrict_family_is_consistent h x hx),
  is_valid_gluing := λ x hx W j hj,
  begin
    let y : family_of_elements P ⇑(pullback j S) := λ Y f hf, x (f ≫ j) (h _ hf),
    have hy : is_consistent y,
    { intros Y₁ Y₂ Z g₁ g₂ f₁ f₂ h₁ h₂ comm,
      apply hx,
      apply reassoc_of comm },
    refine trans hj y _ (x j hj) hy _ _,
    { intros Y f hf,
      rw [←functor_to_types.map_comp_apply, ←op_comp,
          hS.is_valid_gluing _ (restrict_family_is_consistent h x hx) _ hf],
      refl },
    { intros Y f hf,
      rw hx f (𝟙 _) hj (h _ hf) (id_comp _).symm,
      simp }
  end,
  uniqueness := λ x t₁ t₂ hx ht₁ ht₂,
    hS.uniqueness _ _ _ (restrict_family_is_consistent _ _ hx)
                        (is_amalgamation_for_restrict h x t₁ ht₁)
                        (is_amalgamation_for_restrict h x t₂ ht₂) }

def is_sheaf_for_subsieve (P : Cᵒᵖ ⥤ Type v) {S : sieve X} {R : arrows_with_codomain X}
  (h : (S : arrows_with_codomain X) ≤ R)
  (trans : Π ⦃Y⦄ (f : Y ⟶ X), is_sheaf_for P (S.pullback f)) :
  is_sheaf_for P R :=
begin
  apply is_sheaf_for_subsieve_aux P h,
  { simpa using trans (𝟙 _) },
  intros,
  apply (trans f).uniqueness,
end

def is_sheaf_for_bind (P : Cᵒᵖ ⥤ Type v) (S : arrows_with_codomain X)
  (R : Π ⦃Y⦄ ⦃f : Y ⟶ X⦄, S f → sieve Y)
  (hS : is_sheaf_for P S) (hR : ∀ ⦃Y⦄ ⦃f : Y ⟶ X⦄ (H : S f), is_sheaf_for P (R H))
  (hR' : ∀ ⦃Y⦄ ⦃f : Y ⟶ X⦄ (H : S f) ⦃Z⦄ (g : Z ⟶ Y), is_separated_for P ((R H).pullback g)) :
  is_sheaf_for P (sieve.bind S R) :=
{ gluing := λ x hx,
  begin
    let y : Π ⦃Y⦄ ⦃f : Y ⟶ X⦄ (H : S f), family_of_elements P (R H) := λ Y f H Z g hg,
      x _ (arrows_with_codomain.bind_comp _ _ hg),
    have hy : ∀ ⦃Y⦄ ⦃f : Y ⟶ X⦄ (H : S f), is_consistent (y H),
    { intros Y f H Y₁ Y₂ Z g₁ g₂ f₁ f₂ hf₁ hf₂ comm,
      apply hx,
      apply reassoc_of comm },
    apply hS.gluing (λ Y f Hf, (hR Hf).gluing _ (hy Hf)) _,
    intros Y₁ Y₂ Z g₁ g₂ f₁ f₂ h₁ h₂ comm,
    apply hR' h₁ g₁ (λ W k hk, _) _ _ _ _ _,
    { exact x _ (arrows_with_codomain.bind_comp _ _ hk) },
    { rw is_sieve_consistent_iff,
      intros Y' Z' f g hf,
      rw is_sieve_consistent_iff at hx,
      simpa using hx _ g (arrows_with_codomain.bind_comp _ _ hf) },
    { intros Y k hk,
      dsimp,
      have : _ = x _ _ := (hR h₁).is_valid_gluing (y h₁) (hy _) (k ≫ g₁) hk,
      rw ← this,
      simp },
    {

    }
  end

}

def finest_topology (P : Cᵒᵖ ⥤ Type v) : grothendieck_topology C :=
{ sieves := λ X S, ∀ Y (f : Y ⟶ X), nonempty (is_sheaf_for P (S.pullback f)),
  top_mem' := λ X Y f,
  begin
    rw sieve.pullback_top,
    exact ⟨is_sheaf_for_top_sieve P⟩,
  end,
  pullback_stable' := λ X Y S f hS Z g,
  begin
    rw ← pullback_comp,
    apply hS,
  end,
  transitive' := λ X S hS R hR Z g,
  begin
    simp_rw [set.mem_def] at hR,
    simp_rw [set.mem_def] at hS,
    have hS' : Π (Y : C) (f : Y ⟶ X), is_sheaf_for P ⇑(pullback f S),
      intros Y f,
      apply classical.choice (hS Y f),
    clear hS,
    let R' := R.pullback g,
    let S' := S.pullback g,
    -- have hR' : ∀ ⦃Y : C⦄ ⦃f : Y ⟶ X⦄, S f → ∀ (Y_1 : C) (f_1 : Y_1 ⟶ Y), nonempty (is_sheaf_for P ⇑(pullback f_1 (pullback f R))),
    have hR' : Π ⦃Y W : C⦄ (h : W ⟶ Y) ⦃f : Y ⟶ X⦄, S f → is_sheaf_for P (R.pullback (h ≫ f)),
      intros,
      rw pullback_comp,
      apply classical.choice (hR a _ h),
    -- change nonempty (is_sheaf_for P R'),


  end
}

#exit

def is_separated (P : Cᵒᵖ ⥤ Type v) : Prop :=
∀ {X} (S : sieve X), S ∈ J X → is_separated_for P S

@[derive subsingleton]
def is_sheaf (P : Cᵒᵖ ⥤ Type v) : Type (max u v) :=
Π {X} (S : sieve X), S ∈ J X → is_sheaf_for P S

lemma separated_of_sheaf (P : Cᵒᵖ ⥤ Type v) (h : is_sheaf J P) : is_separated J P :=
λ X S hS, (h S hS).uniqueness

#exit

def matching_family (P : Cᵒᵖ ⥤ Type v) (S : sieve X) : Type (max u v) :=
S.functor ⟶ P

def amalgamation {P : Cᵒᵖ ⥤ Type v} {S : sieve X} (γ : matching_family P S) :=
{α : yoneda.obj X ⟶ P // S.functor_inclusion ≫ α = γ}

@[derive subsingleton]
def sheaf_condition_at (S : sieve X) (P : Cᵒᵖ ⥤ Type v) : Type (max u v) :=
Π (γ : matching_family P S), unique (amalgamation γ)

def sheaf_condition_at_top (P : Cᵒᵖ ⥤ Type v) : sheaf_condition_at (⊤ : sieve X) P :=
λ γ,
begin
  refine ⟨⟨⟨inv (⊤:sieve X).functor_inclusion ≫ γ, _⟩⟩, _⟩,
  { simp },
  { rintro ⟨a, ha⟩,
    apply subtype.ext,
    simp [ha] }
end

@[derive subsingleton]
def sheaf_condition (P : Cᵒᵖ ⥤ Type v) : Type (max u v) :=
Π (X : C) (S ∈ J X), sheaf_condition_at S P

def canonical_map (P : Cᵒᵖ ⥤ Type v) (S : sieve X) : (yoneda.obj X ⟶ P) → (S.functor ⟶ P) :=
λ f, S.functor_inclusion ≫ f

def sheaf_condition2 (P : Cᵒᵖ ⥤ Type v) : Prop :=
∀ X (S : sieve X), S ∈ J X → function.bijective (canonical_map P S)

-- noncomputable def sheaf_condition2_equiv (P : Cᵒᵖ ⥤ Type v) : sheaf_condition J P ≃ sheaf_condition2 J P :=
-- { to_fun := λ t X S hS,
--   begin
--     split,
--     { intros α₁ α₂ hα,
--       exact subtype.ext_iff.1 (((t X S _ hS).2 ⟨α₁, hα⟩).trans ((t X S _ hS).2 ⟨α₂, rfl⟩).symm) },
--     { intros γ,
--       exact ⟨_, (t X S γ hS).1.1.2⟩ }
--   end,
--   inv_fun := λ t X S γ hS,
--   begin
--     specialize t X S hS,
--     rw function.bijective_iff_has_inverse at t,
--     choose t ht₁ ht₂ using t,
--     refine ⟨⟨⟨t γ, ht₂ γ⟩⟩, λ a, _⟩,
--     cases a with a ha,
--     apply subtype.ext,
--     dsimp,
--     rw [← ht₁ a, ← ha],
--     refl,
--   end

-- }

def matching_family' (P : Cᵒᵖ ⥤ Type v) {c : C} (S : sieve c) :=
{x : Π {d : C} {f : d ⟶ c}, S.arrows f → P.obj (opposite.op d) //
 ∀ {d e : C} (f : d ⟶ c) (g : e ⟶ d) (h : S.arrows f), x (S.downward_closed h g) = P.map g.op (x h)}

def amalgamation' {P : Cᵒᵖ ⥤ Type v} {c : C} {S : sieve c} (γ : matching_family' P S) :=
{y : P.obj (opposite.op c) // ∀ {d : C} (f : d ⟶ c) (hf : S.arrows f), P.map f.op y = γ.1 hf}

@[derive subsingleton]
def sheaf_condition' (P : Cᵒᵖ ⥤ Type v) : Type (max u v) :=
Π (c : C) (S : sieve c) (γ : matching_family' P S), S ∈ J c → unique (amalgamation' γ)

def matching_family'_equiv_matching_family (P : Cᵒᵖ ⥤ Type v) :
  matching_family' P S ≃ matching_family P S :=
{ to_fun := λ x, ⟨λ _ t, x.1 t.2, λ c c' f, funext $ λ t, x.2 _ _ t.2⟩,
  inv_fun := λ x, ⟨λ d f hf, x.app _ ⟨f, hf⟩, λ d d' f g h, congr_fun (x.2 g.op) ⟨f, h⟩⟩,
  left_inv := λ _, subtype.ext $ funext $ λ _, funext $ λ _, funext $ λ _, rfl,
  right_inv := λ _, by { ext _ ⟨_, _⟩, refl } }

def amalgamation'_equiv_amalgamation (P : Cᵒᵖ ⥤ Type v) (x : matching_family' P S) :
  amalgamation (matching_family'_equiv_matching_family P x) ≃ (amalgamation' x) :=
{ to_fun := λ γ,
  { val := γ.1.app _ (𝟙 X),
    property := λ d f hf,
    begin
      have := congr_fun (γ.1.naturality f.op) (𝟙 _),
      dsimp at this,
      erw ← this,
      rw comp_id,
      have q := congr_arg (λ t, nat_trans.app t (opposite.op d)) γ.2,
      dsimp at q,
      have := congr_fun q ⟨f, hf⟩,
      exact this,
    end },
  inv_fun := λ γ,
  { val :=
    { app := λ c f, P.map f.op γ.1,
      naturality' := λ c c' f, funext $ λ g, functor_to_types.map_comp_apply P g.op f γ.1 },
    property :=
    begin
      ext c ⟨f, hf⟩,
      apply γ.2,
    end },
  left_inv :=
  begin
    rintro ⟨γ₁, γ₂⟩,
    ext d f,
    dsimp,
    rw ← functor_to_types.naturality _ _ γ₁ f.op (𝟙 X),
    dsimp,
    simp,
  end,
  right_inv :=
  begin
    intro γ,
    ext1,
    apply functor_to_types.map_id_apply,
  end }

def sheaf'_equiv_sheaf (P : Cᵒᵖ ⥤ Type v) :
  sheaf_condition J P ≅ sheaf_condition' J P :=
{ hom :=
  begin
    intros h c S γ hS,
    apply equiv.unique (amalgamation'_equiv_amalgamation _ _).symm,
    apply h _ _ hS,
  end,
  inv :=
  begin
    intros h c S hS γ,
    haveI := h _ _ ((matching_family'_equiv_matching_family P).symm γ) hS,
    have := equiv.unique (amalgamation'_equiv_amalgamation P ((matching_family'_equiv_matching_family P).symm γ)),
    simpa using this,
  end }

def finest_topology_sieves (P : Cᵒᵖ ⥤ Type v) : Π (X : C), set (sieve X) :=
λ X S, ∀ Y (f : Y ⟶ X), nonempty (sheaf_condition_at (S.pullback f) P)

def aux_map {Z : C} (S : sieve X) (α : Z ⟶ Y) (f : Y ⟶ X) :
  (S.pullback (α ≫ f)).functor ⟶ (S.pullback f).functor :=
{ app := λ T z, ⟨z.1 ≫ α, by simpa using z.2⟩ }.

def finest_topology (F : Cᵒᵖ ⥤ Type v) : grothendieck_topology C :=
{ sieves := finest_topology_sieves F,
  top_mem' := λ X Y f,
  begin
    rw pullback_top,
    refine ⟨sheaf_condition_at_top _⟩,
  end,
  pullback_stable' := λ X Y S f hS Z g,
  begin
    rw ← pullback_comp,
    apply hS _,
  end,
  transitive' := λ U S hS S' t,
  begin
    intros W f,
    cases hS _ f with hfS,
    refine ⟨λ φ, _⟩,
    let ψ : (S.pullback f).functor ⟶ F,
    { refine ⟨_, _⟩,
      { intros V α,
        have q := t α.2 _ (𝟙 _),
        rw pullback_id at q,
        apply (classical.choice q (aux_map S' α.1 f ≫ φ)).1.1.1.app _ (𝟙 _) },
      { intros V₁ V₂ k,
        sorry,
        -- ext1 α,
        -- dsimp,
        -- have q₁ := t α.2 _ (𝟙 _),
        -- rw pullback_id at q₁,
        -- let z₁ := (classical.choice q₁ (aux_map S' α.1 f ≫ φ)).1.1.1,
        -- have := k.unop ≫ α.1,
        -- -- have q₂ := t (S.downward_closed α.2 k.unop) _ (𝟙 _),
        -- -- rw pullback_id at q₂,
        -- have q₂ : nonempty (sheaf_condition_at (pullback (((pullback f S).functor.map k α).1 ≫ f) S') F),
        --   dsimp [sieve.functor],
        --   rw assoc,
        --   have q₂ := t (S.downward_closed α.2 k.unop) _ (𝟙 _),
        --   rw pullback_id at q₂,
        --   apply q₂,
        -- let z₂ := (classical.choice q₂ (aux_map S' ((S.pullback f).functor.map k α).1 f ≫ φ)).1.1.1,
        -- change z₂.app V₂ (𝟙 _) = F.map k (z₁.app V₁ (𝟙 _)),
        -- have := (classical.choice q₂ (aux_map S' ((S.pullback f).functor.map k α).1 f ≫ φ)).1.1.2,
      }
    },
    refine ⟨⟨⟨(classical.choice (hS _ f) ψ).1.1.1, _⟩⟩, _⟩,
    have := (classical.choice (hS _ f) ψ).1.1.2,
  end
}

variables (C J)

structure Sheaf :=
(P : Cᵒᵖ ⥤ Type v)
(sheaf_cond : sheaf_condition J P)

instance : category (Sheaf C J) := induced_category.category Sheaf.P

end grothendieck_topology
end sheaf

end category_theory
