pull_request_rules:
  - name: automatic merge with strict
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - status-success=continuous-integration/travis-ci/push
    actions:
      merge:
        method: merge
        strict: true
