import category_theory.subobject.mono_over
import category_theory.subobject.basic
import category_theory.subobject.factor_thru
import category_theory.subobject.well_powered
import category_theory.subobject.lattice
