/-
Copyright (c) 2022 Yury Kudryashov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yury Kudryashov
-/
import topology.instances.irrational
import topology.algebra.order.archimedean
import topology.paracompact
import topology.metric_space.metrizable
import topology.metric_space.emetric_paracompact
import data.set.intervals.monotone

/-!
# Sorgenfrey line

In this file we define `sorgenfrey_line` (notation: `ℝₗ`) to be the Sorgenfrey line. It is the real
line with the topology space structure generated by half-open intervals `set.Ico a b`.

We prove that this line is a normal space but its product with itself is not a normal space. In
particular, this implies that the topology on `ℝₗ` is neither metrizable, nor second countable.

## Notations

- `ℝₗ`: Sorgenfrey line.

## TODO

Prove that the Sorgenfrey line is a paracompact space.

-/

open set filter topological_space
open_locale topological_space filter
noncomputable theory

/-- The Sorgenfrey line. It is the real line with the topology space structure generated by
half-open intervals `set.Ico a b`. -/
@[derive [conditionally_complete_linear_order, linear_ordered_field, archimedean]]
def sorgenfrey_line : Type := ℝ

notation `ℝₗ` := sorgenfrey_line

namespace sorgenfrey_line

/-- Ring homomorphism between the Sorgenfrey line and the standard real line. -/
def to_real : ℝₗ ≃+* ℝ := ring_equiv.refl ℝ

instance : topological_space ℝₗ :=
topological_space.generate_from {s : set ℝₗ | ∃ a b : ℝₗ, Ico a b = s}

lemma is_open_Ico (a b : ℝₗ) : is_open (Ico a b) :=
topological_space.generate_open.basic _ ⟨a, b, rfl⟩

lemma is_open_Ici (a : ℝₗ) : is_open (Ici a) :=
Union_Ico_right a ▸ is_open_Union (is_open_Ico a)

lemma nhds_basis_Ico (a : ℝₗ) : (𝓝 a).has_basis ((<) a) (Ico a) :=
begin
  rw topological_space.nhds_generate_from,
  haveI : nonempty {x // x ≤ a} := set.nonempty_Iic_subtype,
  have : (⨅ (x : {i // i ≤ a}), 𝓟 (Ici ↑x)) = 𝓟 (Ici a),
  { refine (is_least.is_glb _).infi_eq,
    exact ⟨⟨⟨a, le_rfl⟩, rfl⟩, forall_range_iff.2 $
      λ b, principal_mono.2 $ Ici_subset_Ici.2 b.2⟩, },
  simp only [mem_set_of_eq, infi_and, infi_exists, @infi_comm _ (_ ∈ _),
    @infi_comm _ (set ℝₗ), infi_infi_eq_right],
  simp_rw [@infi_comm _ ℝₗ (_ ≤ _), infi_subtype', ← Ici_inter_Iio, ← inf_principal, ← inf_infi,
    ← infi_inf, this, infi_subtype],
  suffices : (⨅ x ∈ Ioi a, 𝓟 (Iio x)).has_basis ((<) a) Iio, from this.principal_inf _,
  refine has_basis_binfi_principal _ nonempty_Ioi,
  exact directed_on_iff_directed.2 (directed_of_inf $ λ x y hxy, Iio_subset_Iio hxy),
end

lemma nhds_basis_Ico_rat (a : ℝₗ) :
  (𝓝 a).has_countable_basis (λ r : ℚ, a < r) (λ r, Ico a r) :=
begin
  refine ⟨(nhds_basis_Ico a).to_has_basis (λ b hb, _) (λ r hr, ⟨_, hr, subset.rfl⟩),
    countable_encodable _⟩,
  rcases exists_rat_btwn hb with ⟨r, har, hrb⟩,
  exact ⟨r, har, Ico_subset_Ico_right hrb.le⟩
end

lemma nhds_basis_Ico_inv_nat_pos (a : ℝₗ) :
  (𝓝 a).has_countable_basis (λ n : ℕ, 0 < n) (λ n, Ico a (a + 1 / n)) :=
begin
  refine ⟨(nhds_basis_Ico a).to_has_basis (λ b hb, _)
    (λ n hn, ⟨_, lt_add_of_pos_right _ (one_div_pos.2 $ nat.cast_pos.2 hn), subset.rfl⟩),
    countable_encodable _⟩,
  rcases exists_nat_one_div_lt (sub_pos.2 hb) with ⟨k, hk⟩,
  rw [← nat.cast_add_one] at hk,
  exact ⟨k + 1, k.succ_pos, Ico_subset_Ico_right (le_sub_iff_add_le'.1 hk.le)⟩
end

lemma is_open_iff {s : set ℝₗ} : is_open s ↔ ∀ x ∈ s, ∃ y > x, Ico x y ⊆ s :=
is_open_iff_mem_nhds.trans $ forall₂_congr $ λ x hx, (nhds_basis_Ico x).mem_iff

lemma is_closed_iff {s : set ℝₗ} : is_closed s ↔ ∀ x ∉ s, ∃ y > x, disjoint (Ico x y) s :=
by simp only [← is_open_compl_iff, is_open_iff, mem_compl_iff, subset_compl_iff_disjoint,
  disjoint_iff_inter_eq_empty]

lemma exists_Ico_disjoint_closed {a : ℝₗ} {s : set ℝₗ} (hs : is_closed s) (ha : a ∉ s) :
  ∃ b > a, disjoint (Ico a b) s :=
is_closed_iff.1 hs a ha

@[simp] lemma map_to_real_nhds (a : ℝₗ) : map to_real (𝓝 a) = 𝓝[≥] (to_real a) :=
begin
  refine ((nhds_basis_Ico a).map _).eq_of_same_basis _,
  simpa only [to_real.image_eq_preimage] using nhds_within_Ici_basis_Ico (to_real a)
end

lemma nhds_eq_map (a : ℝₗ) : 𝓝 a = map to_real.symm (𝓝[≥] a.to_real) :=
by simp_rw [← map_to_real_nhds, map_map, (∘), to_real.symm_apply_apply, map_id']

lemma nhds_eq_comap (a : ℝₗ) : 𝓝 a = comap to_real (𝓝[≥] a.to_real) :=
by rw [← map_to_real_nhds, comap_map to_real.injective]

@[continuity] lemma continuous_to_real : continuous to_real :=
continuous_iff_continuous_at.2 $ λ x,
  by { rw [continuous_at, tendsto, map_to_real_nhds], exact inf_le_left }

instance : order_closed_topology ℝₗ :=
⟨is_closed_le_prod.preimage (continuous_to_real.prod_map continuous_to_real)⟩

instance : has_continuous_add ℝₗ :=
begin
  refine ⟨continuous_iff_continuous_at.2 _⟩,
  rintro ⟨x, y⟩,
  simp only [continuous_at, nhds_prod_eq, nhds_eq_map, nhds_eq_comap (x + y), prod_map_map_eq,
    tendsto_comap_iff, tendsto_map'_iff, (∘), ← nhds_within_prod_eq],
  exact (continuous_add.tendsto _).inf (maps_to.tendsto $ λ x hx, add_le_add hx.1 hx.2)
end

lemma is_clopen_Ici (a : ℝₗ) : is_clopen (Ici a) := ⟨is_open_Ici a, is_closed_Ici⟩

lemma is_clopen_Iio (a : ℝₗ) : is_clopen (Iio a) :=
by simpa only [compl_Ici] using (is_clopen_Ici a).compl

lemma is_clopen_Ico (a b : ℝₗ) : is_clopen (Ico a b) :=
(is_clopen_Ici a).inter (is_clopen_Iio b)

instance : totally_disconnected_space ℝₗ :=
begin
  refine ⟨λ s hs' hs x hx y hy, _⟩, clear hs',
  by_contra' hne : x ≠ y,
  wlog hlt : x < y := hne.lt_or_lt using [x y, y x],
  exact hlt.not_le (hs.subset_clopen (is_clopen_Ici y) ⟨y, hy, le_rfl⟩ hx)
end

instance : first_countable_topology ℝₗ := ⟨λ x, (nhds_basis_Ico_rat x).is_countably_generated⟩

instance : normal_space ℝₗ :=
begin
  refine ⟨λ s t hs ht hd, _⟩,
  choose! X hX hXd using λ x (hx : x ∈ s), exists_Ico_disjoint_closed ht (disjoint_left.1 hd hx),
  choose! Y hY hYd using λ y (hy : y ∈ t), exists_Ico_disjoint_closed hs (disjoint_right.1 hd hy),
  refine ⟨⋃ x ∈ s, Ico x (X x), ⋃ y ∈ t, Ico y (Y y), is_open_bUnion $ λ _ _, is_open_Ico _ _,
    is_open_bUnion $ λ _ _, is_open_Ico _ _, _, _, _⟩,
  { exact λ x hx, mem_Union₂.2 ⟨x, hx, left_mem_Ico.2 $ hX x hx⟩ },
  { exact λ y hy, mem_Union₂.2 ⟨y, hy, left_mem_Ico.2 $ hY y hy⟩ },
  { simp only [disjoint_Union_left, disjoint_Union_right, Ico_disjoint_Ico],
    intros y hy x hx,
    clear hs ht hd hX hY,
    cases le_total x y with hle hle,
    { calc min (X x) (Y y) ≤ X x : min_le_left _ _
      ... ≤ y : not_lt.1 (λ hyx, hXd x hx ⟨⟨hle, hyx⟩, hy⟩)
      ... ≤ max x y : le_max_right _ _ },
    { calc min (X x) (Y y) ≤ Y y : min_le_right _ _
      ... ≤ x : not_lt.1 $ λ hxy, hYd y hy ⟨⟨hle, hxy⟩, hx⟩
      ... ≤ max x y : le_max_left _ _ } }
end

lemma dense_range_coe_rat : dense_range (coe : ℚ → ℝₗ) :=
begin
  refine dense_iff_inter_open.2 _,
  rintro U Uo ⟨x, hx⟩,
  rcases is_open_iff.1 Uo _ hx with ⟨y, hxy, hU⟩,
  rcases exists_rat_btwn hxy with ⟨z, hxz, hzy⟩,
  exact ⟨z, hU ⟨hxz.le, hzy⟩, mem_range_self _⟩
end

instance : separable_space ℝₗ := ⟨⟨_, countable_range _, dense_range_coe_rat⟩⟩

lemma is_closed_antidiagonal (c : ℝₗ) : is_closed {x : ℝₗ × ℝₗ | x.1 + x.2 = c} :=
is_closed_singleton.preimage continuous_add

lemma is_clopen_Ici_prod (x : ℝₗ × ℝₗ) : is_clopen (Ici x) :=
(Ici_prod_eq x).symm ▸ (is_clopen_Ici _).prod (is_clopen_Ici _)

lemma is_closed_of_subset_antidiagonal {s : set (ℝₗ × ℝₗ)} {c : ℝₗ}
  (hs : ∀ x ∈ s, (x : _).1 + x.2 = c) : is_closed s :=
begin
  rw [← closure_subset_iff_is_closed],
  rintro ⟨x, y⟩ H,
  obtain rfl : x + y = c,
  { change (x, y) ∈ {p : ℝₗ × ℝₗ | p.1 + p.2 = c},
    exact closure_minimal (hs : s ⊆ {x | x.1 + x.2 = c}) (is_closed_antidiagonal c) H },
  rcases mem_closure_iff.1 H (Ici (x, y)) (is_clopen_Ici_prod _).1 le_rfl
    with ⟨⟨x', y'⟩, ⟨hx : x ≤ x', hy : y ≤ y'⟩, H⟩,
  convert H,
  { refine hx.antisymm _,
    rwa [← add_le_add_iff_right, hs _ H, add_le_add_iff_left] },
  { refine hy.antisymm _,
    rwa [← add_le_add_iff_left, hs _ H, add_le_add_iff_right] }
end

lemma nhds_prod_basis_inv_nat_pos (x : ℝₗ × ℝₗ) :
  (𝓝 x).has_basis (λ n : ℕ, 0 < n) (λ n, Ico x.1 (x.1 + 1 / n) ×ˢ Ico x.2 (x.2 + 1 / n)) :=
begin
  cases x with x y,
  simp only [nhds_prod_eq],
  refine (nhds_basis_Ico_inv_nat_pos x).to_has_basis.prod'
    (nhds_basis_Ico_inv_nat_pos y).to_has_basis (λ i j hi hj, _),
  refine ⟨max i j, lt_max_iff.2 $ or.inl hi, Ico_subset_Ico_right _, Ico_subset_Ico_right _⟩;
    refine add_le_add_left (one_div_le_one_div_of_le (nat.cast_pos.2 ‹_›) $ nat.mono_cast _) _,
  exacts [le_max_left _ _, le_max_right _ _],
end

lemma not_normal_space_prod : ¬normal_space (ℝₗ × ℝₗ) :=
begin
  have h₀ : ∀ {n : ℕ}, 0 < n → (0 : ℝ) < 1 / n, from λ n hn, one_div_pos.2 (nat.cast_pos.2 hn),
  introI,
  set S := {x : ℝₗ × ℝₗ | x.1 + x.2 = 0 ∧ ∃ r : ℚ, ↑r = x.1},
  set T := {x : ℝₗ × ℝₗ | x.1 + x.2 = 0 ∧ irrational x.1.to_real},
  have hSc : is_closed S, from is_closed_of_subset_antidiagonal (λ x hx, hx.1),
  have hTc : is_closed T, from is_closed_of_subset_antidiagonal (λ x hx, hx.1),
  have hd : disjoint S T,
  { rintro ⟨x, y⟩ ⟨⟨-, r, rfl : _ = x⟩, -, hr⟩,
    exact r.not_irrational hr },
  rcases normal_separation hSc hTc hd with ⟨U, V, Uo, Vo, SU, TV, UV⟩,
  have : ∀ x : ℝₗ, irrational x.to_real →
    ∃ (k : ℕ) (hk : 0 < k), Ico x (x + 1 / k) ×ˢ Ico (-x) (-x + 1 / k) ⊆ V,
  { intros x hx,
    have hV : V ∈ 𝓝 (x, -x), from Vo.mem_nhds (@TV (x, -x) ⟨add_neg_self x, hx⟩),
    exact (nhds_prod_basis_inv_nat_pos _).mem_iff.1 hV },
  choose! k hk₀ hkV,
  set C : ℕ → set ℝ := λ n, closure {x | irrational x ∧ k (to_real.symm x) = n},
  have H : {x : ℝ | irrational x} ⊆ ⋃ n ∈ {n : ℕ | 0 < n}, C n,
    from λ x hx, mem_bUnion (hk₀ (to_real.symm x) hx) (subset_closure ⟨hx, rfl⟩),
  have Hd : dense (⋃ n ∈ {n : ℕ | 0 < n}, interior (C n)),
    from is_Gδ_irrational.dense_bUnion_interior_of_closed dense_irrational
      (countable_encodable {n : ℕ | 0 < n}) (λ _ _, is_closed_closure) H,
  obtain ⟨N, hN₀, hN⟩ : ∃ n : ℕ, 0 < n ∧ (interior $ C n).nonempty,
    by simpa only [nonempty_Union, exists_prop] using Hd.nonempty,
  rcases rat.dense_range_cast.exists_mem_open is_open_interior hN with ⟨r, hr⟩,
  have hrU : ((r, -r) : ℝₗ × ℝₗ) ∈ U, from @SU (r, -r) ⟨add_neg_self _, r, rfl⟩,
  rcases (nhds_prod_basis_inv_nat_pos _).mem_iff.1 (Uo.mem_nhds hrU) with ⟨n, hn₀, hn⟩,
  dsimp only at hn,
  obtain ⟨ε, ε₀, hεn, hεN⟩ : ∃ ε : ℝ, 0 < ε ∧ ε ≤ 1 / n ∧ ε ≤ 1 / N,
    from ⟨min (1 / n) (1 / N), lt_min (h₀ hn₀) (h₀ hN₀), min_le_left _ _, min_le_right _ _⟩,
  obtain ⟨x, hxε, hx_irr, rfl⟩ :
    ∃ x : ℝ, x ∈ Ioo (r : ℝ) (r + ε) ∧ irrational x ∧ k (to_real.symm x) = N,
  { have : (r : ℝ) ∈ closure (Ioo (r : ℝ) (r + ε)),
    { rw [closure_Ioo]; simp [ε₀.ne', ε₀.le] },
    rcases mem_closure_iff_nhds.1 this _ (mem_interior_iff_mem_nhds.1 hr) with ⟨x', hx', hx'ε⟩,
    exact mem_closure_iff.1 hx' _ is_open_Ioo hx'ε },
  refine @UV (to_real.symm x, -r) ⟨hn ⟨_, _⟩, hkV x hx_irr ⟨_, _⟩⟩,
  { exact ⟨hxε.1.le, hxε.2.trans_le $ add_le_add_left hεn _⟩ },
  { exact left_mem_Ico.2 (lt_add_of_pos_right _ (h₀ hn₀)) },
  { exact left_mem_Ico.2 (lt_add_of_pos_right _ (h₀ $ hk₀ x hx_irr)) },
  { refine ⟨neg_le_neg hxε.1.le, _⟩,
    simp only [add_neg_lt_iff_le_add', lt_neg_add_iff_add_lt],
    exact hxε.2.trans_le (add_le_add_left hεN _) }
end

lemma not_metrizable_space : ¬metrizable_space ℝₗ :=
begin
  introI,
  letI := metrizable_space_metric ℝₗ,
  exact not_normal_space_prod infer_instance
end

lemma not_second_countable_topology : ¬second_countable_topology ℝₗ :=
by { introI, exact not_metrizable_space (metrizable_space_of_regular_second_countable _) }

end sorgenfrey_line
