import
  algebra.group
  algebra.ring
  algebra.field
  algebra.order
  algebra.ordered_monoid
  algebra.ordered_group
  algebra.ordered_ring
  algebra.functions
  algebra.group_power
  algebra.module
